name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

jobs:
  build:
    runs-on: macOS-latest

    strategy:
        matrix:
          node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
    - name: Install dependencies
      run: |
        npm ci
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_PRIVATE_READ_TOKEN }}
    - name: Update README
      run: |-
        npm start
        cat README.md
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "rupareliyaravi@example.com"
        git config --global user.name "Ravi Rupareliya"
        git commit -m "Instagram feed updated." -a || echo "No changes to commit"
        git push
